import { uid } from "./id";
import {
  ASPECT_RATIOS,
  AdTemplate,
  BackgroundFill,
  Layer,
  Scene,
  ShapeLayer,
  StickerLayer,
  TextLayer,
  ImageLayer,
  TemplateBuildOpts,
} from "./types";

/* ──────────────────────────────────────────────────────────────────────────
 *  Layer factory helpers
 *  All coordinates are normalized 0..1 so templates render identically
 *  across every Meta aspect ratio (1:1, 4:5, 9:16, 16:9).
 * ────────────────────────────────────────────────────────────────────────── */

function text(partial: Partial<TextLayer> & Pick<TextLayer, "text">): TextLayer {
  return {
    id: uid("t"),
    type: "text",
    x: 0.08,
    y: 0.4,
    width: 0.84,
    height: 0.15,
    rotation: 0,
    opacity: 1,
    animation: "fadeIn",
    animationDelay: 0,
    animationDuration: 0.5,
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
    fontWeight: 800,
    fontSize: 0.075,
    lineHeight: 1.05,
    letterSpacing: -0.01,
    color: "#0f172a",
    align: "center",
    paddingX: 0,
    paddingY: 0,
    borderRadius: 0,
    uppercase: false,
    ...partial,
  };
}

function shape(partial: Partial<ShapeLayer> & Pick<ShapeLayer, "shape" | "fill">): ShapeLayer {
  return {
    id: uid("s"),
    type: "shape",
    x: 0.1,
    y: 0.1,
    width: 0.8,
    height: 0.1,
    rotation: 0,
    opacity: 1,
    animation: "none",
    animationDelay: 0,
    animationDuration: 0.4,
    borderRadius: 0.02,
    ...partial,
  };
}

function image(partial: Partial<ImageLayer> & Pick<ImageLayer, "src">): ImageLayer {
  return {
    id: uid("i"),
    type: "image",
    x: 0,
    y: 0,
    width: 1,
    height: 1,
    rotation: 0,
    opacity: 1,
    animation: "kenBurns",
    animationDelay: 0,
    animationDuration: 4,
    fit: "cover",
    borderRadius: 0,
    ...partial,
  };
}

function sticker(emoji: string, partial: Partial<StickerLayer> = {}): StickerLayer {
  return {
    id: uid("st"),
    type: "sticker",
    emoji,
    x: 0.45,
    y: 0.05,
    width: 0.1,
    height: 0.1,
    rotation: 0,
    opacity: 1,
    fontSize: 0.08,
    animation: "pulse",
    animationDelay: 0,
    animationDuration: 1,
    ...partial,
  };
}

function scene(partial: Partial<Scene> & Pick<Scene, "background" | "layers">): Scene {
  return {
    id: uid("sc"),
    name: "Scene",
    duration: 2.5,
    transitionIn: "fade",
    transitionInDuration: 0.3,
    ...partial,
  };
}

const grad = (from: string, to: string, angle = 135): BackgroundFill => ({
  kind: "gradient",
  from,
  to,
  angle,
});

const heroPlaceholder = (label: string): BackgroundFill => ({
  kind: "gradient",
  from: "#1f2937",
  to: "#111827",
  angle: 180,
});

/* ──────────────────────────────────────────────────────────────────────────
 *  TEMPLATES
 *  Each is a structured, proven Meta video-ad pattern adapted for junk
 *  removal in Tampa. They follow the Hook → Promise → Proof → Offer → CTA
 *  cadence that consistently wins on Reels and Feed placements.
 * ────────────────────────────────────────────────────────────────────────── */

const TEMPLATES: AdTemplate[] = [
  /* ─── 1. Pattern interrupt + free quote ─────────────────────────────── */
  {
    id: "tpl-free-quote",
    name: "Tampa Free Quote — Pattern Interrupt",
    goal: "free-quote",
    description:
      "Bold pattern-interrupt opener, problem call-out, then a no-brainer free quote CTA. Best-tested hook for cold Tampa traffic.",
    recommendedAspect: "9:16",
    preview: {
      background: grad("#16a34a", "#065f46"),
      headline: "STOP Living With That Junk",
      sub: "Free Tampa quote in 60 sec",
      accent: "#facc15",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Hook",
        duration: 2.2,
        background: grad("#16a34a", "#065f46", 160),
        transitionIn: "none",
        layers: [
          sticker("🚮", { x: 0.4, y: 0.18, width: 0.2, height: 0.2, fontSize: 0.18 }),
          text({
            text: "STOP",
            y: 0.42,
            fontSize: 0.18,
            color: "#ffffff",
            fontWeight: 900,
            letterSpacing: -0.02,
            animation: "zoomIn",
            animationDuration: 0.4,
          }),
          text({
            text: "Living with that junk in your garage.",
            y: 0.62,
            fontSize: 0.058,
            color: "#fef3c7",
            fontWeight: 600,
            animation: "slideUp",
            animationDelay: 0.3,
            animationDuration: 0.5,
          }),
        ],
      }),
      scene({
        name: "Promise",
        duration: 2.4,
        background: grad("#0f172a", "#1e293b", 180),
        transitionIn: "slideUp",
        layers: [
          text({
            text: "Same-day pickup in Tampa Bay.",
            y: 0.32,
            fontSize: 0.075,
            color: "#ffffff",
            fontWeight: 800,
            animation: "fadeIn",
          }),
          text({
            text: "We load. We sweep. We're gone.",
            y: 0.48,
            fontSize: 0.055,
            color: "#94a3b8",
            fontWeight: 500,
            animation: "slideUp",
            animationDelay: 0.4,
          }),
          shape({
            shape: "rect",
            fill: palette.accent,
            x: 0.2,
            y: 0.66,
            width: 0.6,
            height: 0.09,
            borderRadius: 0.05,
            animation: "zoomIn",
            animationDelay: 0.8,
          }),
          text({
            text: brand.offer.toUpperCase(),
            y: 0.685,
            fontSize: 0.045,
            color: "#0f172a",
            fontWeight: 900,
            letterSpacing: 0.02,
            animation: "fadeIn",
            animationDelay: 1.0,
          }),
        ],
      }),
      scene({
        name: "CTA",
        duration: 2.4,
        background: grad(palette.primary, "#065f46", 150),
        transitionIn: "zoom",
        layers: [
          text({
            text: brand.cta,
            y: 0.32,
            fontSize: 0.085,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
          }),
          shape({
            shape: "rect",
            fill: "#ffffff",
            x: 0.15,
            y: 0.5,
            width: 0.7,
            height: 0.12,
            borderRadius: 0.06,
            animation: "fadeIn",
            animationDelay: 0.4,
          }),
          text({
            text: brand.website,
            y: 0.525,
            fontSize: 0.06,
            color: palette.secondary,
            fontWeight: 800,
            animation: "fadeIn",
            animationDelay: 0.6,
          }),
          text({
            text: `Call ${brand.phone}`,
            y: 0.7,
            fontSize: 0.045,
            color: "#fef3c7",
            fontWeight: 600,
            animation: "fadeIn",
            animationDelay: 0.9,
          }),
          text({
            text: brand.serviceArea,
            y: 0.82,
            fontSize: 0.03,
            color: "#ffffff",
            opacity: 0.75,
            fontWeight: 500,
            animation: "fadeIn",
            animationDelay: 1.1,
          }),
        ],
      }),
    ],
  },

  /* ─── 2. Before/After transformation ────────────────────────────────── */
  {
    id: "tpl-before-after",
    name: "Before & After — Visual Proof",
    goal: "before-after",
    description:
      "The single highest-saving-rate format in junk removal. Reveal a cluttered garage, then the empty 'after' with a satisfying transition.",
    recommendedAspect: "4:5",
    preview: {
      background: grad("#dc2626", "#7f1d1d"),
      headline: "Before → After",
      sub: "Watch the transformation",
      accent: "#facc15",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Before",
        duration: 2.0,
        background: brand.beforeImage
          ? { kind: "image", src: brand.beforeImage, fit: "cover", overlay: "rgba(0,0,0,0.45)" }
          : grad("#7f1d1d", "#171717", 180),
        transitionIn: "none",
        layers: [
          shape({
            shape: "rect",
            fill: "#dc2626",
            x: 0.08,
            y: 0.08,
            width: 0.35,
            height: 0.08,
            borderRadius: 0.04,
          }),
          text({
            text: "BEFORE",
            x: 0.08,
            y: 0.092,
            width: 0.35,
            height: 0.06,
            fontSize: 0.05,
            color: "#ffffff",
            fontWeight: 900,
            letterSpacing: 0.05,
          }),
          text({
            text: "Garage looking like a dumpster?",
            y: 0.78,
            fontSize: 0.058,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideUp",
            animationDelay: 0.4,
          }),
        ],
      }),
      scene({
        name: "After",
        duration: 2.2,
        background: brand.afterImage
          ? { kind: "image", src: brand.afterImage, fit: "cover", overlay: "rgba(255,255,255,0.05)" }
          : grad("#16a34a", "#052e16", 180),
        transitionIn: "slideLeft",
        layers: [
          shape({
            shape: "rect",
            fill: palette.primary,
            x: 0.57,
            y: 0.08,
            width: 0.35,
            height: 0.08,
            borderRadius: 0.04,
          }),
          text({
            text: "AFTER",
            x: 0.57,
            y: 0.092,
            width: 0.35,
            height: 0.06,
            fontSize: 0.05,
            color: "#ffffff",
            fontWeight: 900,
            letterSpacing: 0.05,
          }),
          text({
            text: "Cleared in under an hour.",
            y: 0.78,
            fontSize: 0.062,
            color: "#ffffff",
            fontWeight: 800,
            animation: "slideUp",
            animationDelay: 0.4,
          }),
        ],
      }),
      scene({
        name: "Offer",
        duration: 2.2,
        background: grad(palette.primary, "#065f46", 150),
        transitionIn: "zoom",
        layers: [
          text({
            text: brand.offer,
            y: 0.3,
            fontSize: 0.085,
            color: "#fde047",
            fontWeight: 900,
            animation: "zoomIn",
          }),
          text({
            text: "Same-day service across Tampa Bay",
            y: 0.46,
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 500,
            animation: "fadeIn",
            animationDelay: 0.4,
          }),
          shape({
            shape: "rect",
            fill: "#ffffff",
            x: 0.15,
            y: 0.62,
            width: 0.7,
            height: 0.11,
            borderRadius: 0.06,
            animation: "slideUp",
            animationDelay: 0.6,
          }),
          text({
            text: brand.cta,
            y: 0.645,
            fontSize: 0.055,
            color: palette.secondary,
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.8,
          }),
          text({
            text: brand.website,
            y: 0.84,
            fontSize: 0.04,
            color: "#ffffff",
            opacity: 0.9,
            fontWeight: 600,
            animation: "fadeIn",
            animationDelay: 1.0,
          }),
        ],
      }),
    ],
  },

  /* ─── 3. 5-star social proof ────────────────────────────────────────── */
  {
    id: "tpl-social-proof",
    name: "5-Star Tampa Reviews — Social Proof",
    goal: "social-proof",
    description:
      "Lead with a real review, then stack the rating + review count to lower buyer risk. Outperforms generic 'about us' creative every time.",
    recommendedAspect: "1:1",
    preview: {
      background: grad("#0f172a", "#1e293b"),
      headline: "★★★★★",
      sub: "Tampa's highest-rated crew",
      accent: "#facc15",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Stars",
        duration: 1.6,
        background: grad("#0f172a", "#1e293b", 180),
        transitionIn: "none",
        layers: [
          text({
            text: "★★★★★",
            y: 0.32,
            fontSize: 0.15,
            color: "#facc15",
            fontWeight: 900,
            animation: "zoomIn",
            animationDuration: 0.4,
          }),
          text({
            text: "1,200+ Tampa 5-star reviews",
            y: 0.55,
            fontSize: 0.055,
            color: "#ffffff",
            fontWeight: 700,
            animation: "fadeIn",
            animationDelay: 0.4,
          }),
        ],
      }),
      scene({
        name: "Quote",
        duration: 3.2,
        background: grad("#1e293b", "#0f172a", 200),
        transitionIn: "fade",
        layers: [
          text({
            text: "★★★★★",
            y: 0.12,
            fontSize: 0.06,
            color: "#facc15",
            fontWeight: 900,
            animation: "fadeIn",
          }),
          text({
            text: `"${brand.reviewQuote}"`,
            y: 0.28,
            x: 0.08,
            width: 0.84,
            height: 0.45,
            fontSize: 0.058,
            color: "#ffffff",
            fontWeight: 600,
            italic: true,
            lineHeight: 1.25,
            animation: "slideUp",
            animationDelay: 0.3,
            animationDuration: 0.6,
          }),
          text({
            text: `— ${brand.reviewerName}`,
            y: 0.78,
            fontSize: 0.035,
            color: "#94a3b8",
            fontWeight: 500,
            animation: "fadeIn",
            animationDelay: 0.8,
          }),
        ],
      }),
      scene({
        name: "CTA",
        duration: 2.0,
        background: grad(palette.primary, "#065f46", 150),
        transitionIn: "slideUp",
        layers: [
          text({
            text: "See why Tampa picks us.",
            y: 0.3,
            fontSize: 0.07,
            color: "#ffffff",
            fontWeight: 900,
            animation: "fadeIn",
          }),
          shape({
            shape: "rect",
            fill: "#ffffff",
            x: 0.15,
            y: 0.5,
            width: 0.7,
            height: 0.12,
            borderRadius: 0.06,
            animation: "zoomIn",
            animationDelay: 0.3,
          }),
          text({
            text: brand.cta,
            y: 0.525,
            fontSize: 0.055,
            color: palette.secondary,
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.5,
          }),
          text({
            text: brand.website,
            y: 0.78,
            fontSize: 0.04,
            color: "#ffffff",
            opacity: 0.9,
            fontWeight: 600,
            animation: "fadeIn",
            animationDelay: 0.7,
          }),
        ],
      }),
    ],
  },

  /* ─── 4. Same-day urgency ───────────────────────────────────────────── */
  {
    id: "tpl-same-day",
    name: "Same-Day Tampa — Urgency Driver",
    goal: "same-day-service",
    description:
      "Hard urgency hook with a ticking-clock vibe. Best when paired with retargeting audiences who already viewed your site.",
    recommendedAspect: "9:16",
    preview: {
      background: grad("#dc2626", "#0f172a"),
      headline: "Gone Today.",
      sub: "Book before 2pm",
      accent: "#facc15",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Clock",
        duration: 1.8,
        background: grad("#0f172a", "#1e1b4b", 200),
        transitionIn: "none",
        layers: [
          sticker("⏰", { x: 0.4, y: 0.18, width: 0.2, height: 0.2, fontSize: 0.2 }),
          text({
            text: "Book by 2pm.",
            y: 0.46,
            fontSize: 0.09,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.2,
          }),
          text({
            text: "It's gone today.",
            y: 0.6,
            fontSize: 0.09,
            color: "#facc15",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.5,
          }),
        ],
      }),
      scene({
        name: "How",
        duration: 2.6,
        background: grad("#1e293b", "#0f172a", 180),
        transitionIn: "slideUp",
        layers: [
          text({
            text: "How it works",
            y: 0.1,
            fontSize: 0.04,
            color: "#94a3b8",
            fontWeight: 600,
            uppercase: true,
            letterSpacing: 0.1,
            animation: "fadeIn",
          }),
          text({
            text: "1. Book online in 60 sec",
            y: 0.28,
            fontSize: 0.05,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            x: 0.12,
            width: 0.76,
            animation: "slideLeft",
            animationDelay: 0.3,
          }),
          text({
            text: "2. We arrive in a 2-hr window",
            y: 0.45,
            fontSize: 0.05,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            x: 0.12,
            width: 0.76,
            animation: "slideLeft",
            animationDelay: 0.55,
          }),
          text({
            text: "3. Junk gone. Driveway swept.",
            y: 0.62,
            fontSize: 0.05,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            x: 0.12,
            width: 0.76,
            animation: "slideLeft",
            animationDelay: 0.8,
          }),
          text({
            text: "Upfront pricing. No surprises.",
            y: 0.82,
            fontSize: 0.04,
            color: "#86efac",
            fontWeight: 600,
            animation: "fadeIn",
            animationDelay: 1.1,
          }),
        ],
      }),
      scene({
        name: "CTA",
        duration: 2.0,
        background: grad(palette.primary, "#052e16", 150),
        transitionIn: "zoom",
        layers: [
          text({
            text: brand.cta,
            y: 0.3,
            fontSize: 0.08,
            color: "#ffffff",
            fontWeight: 900,
            animation: "zoomIn",
          }),
          shape({
            shape: "rect",
            fill: "#facc15",
            x: 0.15,
            y: 0.52,
            width: 0.7,
            height: 0.12,
            borderRadius: 0.06,
            animation: "slideUp",
            animationDelay: 0.3,
          }),
          text({
            text: brand.website,
            y: 0.545,
            fontSize: 0.055,
            color: "#0f172a",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.5,
          }),
          text({
            text: brand.serviceArea,
            y: 0.82,
            fontSize: 0.03,
            color: "#ffffff",
            opacity: 0.85,
            fontWeight: 500,
            animation: "fadeIn",
            animationDelay: 0.7,
          }),
        ],
      }),
    ],
  },

  /* ─── 5. Limited-time offer ─────────────────────────────────────────── */
  {
    id: "tpl-offer",
    name: "Limited-Time Offer — Deal Stack",
    goal: "limited-offer",
    description:
      "Stack the discount + the bonus + the guarantee. Best for cold-traffic prospecting with a clear dollar-amount hook.",
    recommendedAspect: "4:5",
    preview: {
      background: grad("#facc15", "#f59e0b"),
      headline: "$50 OFF",
      sub: "This week only",
      accent: "#dc2626",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Offer",
        duration: 2.0,
        background: grad("#facc15", "#f59e0b", 160),
        transitionIn: "none",
        layers: [
          text({
            text: "TAMPA SPECIAL",
            y: 0.15,
            fontSize: 0.045,
            color: "#7c2d12",
            fontWeight: 900,
            letterSpacing: 0.15,
            animation: "fadeIn",
          }),
          text({
            text: brand.offer.split(" ")[0] || "$50 OFF",
            y: 0.32,
            fontSize: 0.22,
            color: "#0f172a",
            fontWeight: 900,
            animation: "zoomIn",
            animationDuration: 0.5,
          }),
          text({
            text: brand.offer.split(" ").slice(1).join(" ") || "Your First Pickup",
            y: 0.6,
            fontSize: 0.06,
            color: "#0f172a",
            fontWeight: 800,
            animation: "slideUp",
            animationDelay: 0.4,
          }),
          text({
            text: "Code: TAMPA50",
            y: 0.78,
            fontSize: 0.05,
            color: "#7c2d12",
            fontWeight: 800,
            animation: "fadeIn",
            animationDelay: 0.7,
          }),
        ],
      }),
      scene({
        name: "Stack",
        duration: 2.6,
        background: grad("#0f172a", "#1e293b", 180),
        transitionIn: "slideUp",
        layers: [
          text({
            text: "Plus you get",
            y: 0.12,
            fontSize: 0.04,
            color: "#94a3b8",
            fontWeight: 600,
            uppercase: true,
            letterSpacing: 0.12,
            animation: "fadeIn",
          }),
          text({
            text: "✓  Free on-site quote",
            y: 0.28,
            fontSize: 0.052,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            x: 0.12,
            width: 0.76,
            animation: "slideLeft",
            animationDelay: 0.2,
          }),
          text({
            text: "✓  Donations & recycling included",
            y: 0.43,
            fontSize: 0.052,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            x: 0.12,
            width: 0.76,
            animation: "slideLeft",
            animationDelay: 0.45,
          }),
          text({
            text: "✓  Licensed & insured locally",
            y: 0.58,
            fontSize: 0.052,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            x: 0.12,
            width: 0.76,
            animation: "slideLeft",
            animationDelay: 0.7,
          }),
          text({
            text: "✓  Driveway swept clean",
            y: 0.73,
            fontSize: 0.052,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            x: 0.12,
            width: 0.76,
            animation: "slideLeft",
            animationDelay: 0.95,
          }),
        ],
      }),
      scene({
        name: "CTA",
        duration: 2.0,
        background: grad(palette.primary, "#052e16", 150),
        transitionIn: "fade",
        layers: [
          text({
            text: "Ends Sunday.",
            y: 0.18,
            fontSize: 0.06,
            color: "#fde047",
            fontWeight: 800,
            animation: "fadeIn",
          }),
          text({
            text: brand.cta,
            y: 0.32,
            fontSize: 0.075,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.2,
          }),
          shape({
            shape: "rect",
            fill: "#ffffff",
            x: 0.15,
            y: 0.52,
            width: 0.7,
            height: 0.12,
            borderRadius: 0.06,
            animation: "zoomIn",
            animationDelay: 0.5,
          }),
          text({
            text: brand.website,
            y: 0.545,
            fontSize: 0.055,
            color: palette.secondary,
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.7,
          }),
        ],
      }),
    ],
  },

  /* ─── 6. Trust builder — Local / family-owned ───────────────────────── */
  {
    id: "tpl-trust",
    name: "Tampa Local — Trust Builder",
    goal: "trust-builder",
    description:
      "Counters the 'random dude in a truck' fear. Lean into local, licensed, insured, uniformed — the messaging that converts cautious homeowners.",
    recommendedAspect: "1:1",
    preview: {
      background: grad("#0369a1", "#075985"),
      headline: "Tampa Owned. Tampa Trusted.",
      sub: "Licensed • Insured • Background-checked",
      accent: "#facc15",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Identity",
        duration: 2.4,
        background: brand.heroImage
          ? { kind: "image", src: brand.heroImage, fit: "cover", overlay: "rgba(7,89,133,0.6)" }
          : grad("#0369a1", "#075985", 180),
        transitionIn: "none",
        layers: [
          sticker("🌴", { x: 0.05, y: 0.06, width: 0.12, height: 0.12, fontSize: 0.08, animation: "none" }),
          text({
            text: "TAMPA OWNED",
            y: 0.1,
            fontSize: 0.04,
            color: "#fde047",
            fontWeight: 900,
            letterSpacing: 0.18,
            animation: "fadeIn",
          }),
          text({
            text: brand.companyName,
            y: 0.34,
            fontSize: 0.11,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.3,
          }),
          text({
            text: brand.tagline,
            y: 0.55,
            fontSize: 0.05,
            color: "#e0f2fe",
            fontWeight: 600,
            animation: "fadeIn",
            animationDelay: 0.7,
          }),
        ],
      }),
      scene({
        name: "Badges",
        duration: 2.4,
        background: grad("#0f172a", "#1e293b", 180),
        transitionIn: "slideUp",
        layers: [
          text({
            text: "What you can count on",
            y: 0.1,
            fontSize: 0.038,
            color: "#94a3b8",
            fontWeight: 600,
            uppercase: true,
            letterSpacing: 0.12,
            animation: "fadeIn",
          }),
          text({
            text: "🛡  Fully licensed & insured",
            y: 0.3,
            fontSize: 0.048,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            x: 0.1,
            width: 0.8,
            animation: "slideLeft",
            animationDelay: 0.2,
          }),
          text({
            text: "👕  Uniformed, background-checked crew",
            y: 0.46,
            fontSize: 0.048,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            x: 0.1,
            width: 0.8,
            animation: "slideLeft",
            animationDelay: 0.45,
          }),
          text({
            text: "💵  Upfront flat pricing",
            y: 0.62,
            fontSize: 0.048,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            x: 0.1,
            width: 0.8,
            animation: "slideLeft",
            animationDelay: 0.7,
          }),
          text({
            text: "♻️  Donation-first disposal",
            y: 0.78,
            fontSize: 0.048,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            x: 0.1,
            width: 0.8,
            animation: "slideLeft",
            animationDelay: 0.95,
          }),
        ],
      }),
      scene({
        name: "CTA",
        duration: 2.0,
        background: grad(palette.primary, "#065f46", 150),
        transitionIn: "fade",
        layers: [
          text({
            text: "Your Tampa neighbors trust us.",
            y: 0.28,
            fontSize: 0.058,
            color: "#ffffff",
            fontWeight: 700,
            animation: "fadeIn",
          }),
          shape({
            shape: "rect",
            fill: "#ffffff",
            x: 0.15,
            y: 0.48,
            width: 0.7,
            height: 0.12,
            borderRadius: 0.06,
            animation: "slideUp",
            animationDelay: 0.3,
          }),
          text({
            text: brand.cta,
            y: 0.505,
            fontSize: 0.055,
            color: palette.secondary,
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.5,
          }),
          text({
            text: brand.website,
            y: 0.78,
            fontSize: 0.04,
            color: "#ffffff",
            opacity: 0.9,
            fontWeight: 600,
            animation: "fadeIn",
            animationDelay: 0.7,
          }),
        ],
      }),
    ],
  },

  /* ─── 7. Service area dominator ─────────────────────────────────────── */
  {
    id: "tpl-service-area",
    name: "Tampa Service Area Dominator",
    goal: "service-area",
    description:
      "Geo-anchored creative that scrolls Tampa neighborhoods. Pair with location-targeted ad sets to dominate local searches.",
    recommendedAspect: "9:16",
    preview: {
      background: grad("#065f46", "#022c22"),
      headline: "We're in your neighborhood.",
      sub: "Tampa Bay's #1 booked crew",
      accent: "#facc15",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Map",
        duration: 2.0,
        background: grad("#0f172a", "#0c4a6e", 200),
        transitionIn: "none",
        layers: [
          sticker("📍", { x: 0.4, y: 0.18, width: 0.2, height: 0.2, fontSize: 0.18 }),
          text({
            text: "We're in your",
            y: 0.46,
            fontSize: 0.08,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.2,
          }),
          text({
            text: "Tampa neighborhood.",
            y: 0.6,
            fontSize: 0.08,
            color: "#facc15",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.45,
          }),
        ],
      }),
      scene({
        name: "Neighborhoods",
        duration: 3.0,
        background: grad("#065f46", "#022c22", 180),
        transitionIn: "slideUp",
        layers: [
          text({
            text: "Booking today in",
            y: 0.08,
            fontSize: 0.038,
            color: "#a7f3d0",
            fontWeight: 600,
            uppercase: true,
            letterSpacing: 0.12,
            animation: "fadeIn",
          }),
          text({
            text: "South Tampa",
            y: 0.22,
            fontSize: 0.07,
            color: "#ffffff",
            fontWeight: 800,
            animation: "slideLeft",
            animationDelay: 0.1,
          }),
          text({
            text: "Hyde Park • Westchase",
            y: 0.34,
            fontSize: 0.05,
            color: "#d1fae5",
            fontWeight: 600,
            animation: "slideLeft",
            animationDelay: 0.3,
          }),
          text({
            text: "Brandon • Riverview",
            y: 0.44,
            fontSize: 0.05,
            color: "#d1fae5",
            fontWeight: 600,
            animation: "slideLeft",
            animationDelay: 0.5,
          }),
          text({
            text: "Wesley Chapel • Lutz",
            y: 0.54,
            fontSize: 0.05,
            color: "#d1fae5",
            fontWeight: 600,
            animation: "slideLeft",
            animationDelay: 0.7,
          }),
          text({
            text: "St. Pete • Clearwater",
            y: 0.64,
            fontSize: 0.05,
            color: "#d1fae5",
            fontWeight: 600,
            animation: "slideLeft",
            animationDelay: 0.9,
          }),
          text({
            text: "+ anywhere within 30 mi",
            y: 0.8,
            fontSize: 0.038,
            color: "#fde047",
            fontWeight: 700,
            animation: "fadeIn",
            animationDelay: 1.2,
          }),
        ],
      }),
      scene({
        name: "CTA",
        duration: 2.0,
        background: grad(palette.primary, "#022c22", 150),
        transitionIn: "fade",
        layers: [
          text({
            text: brand.cta,
            y: 0.32,
            fontSize: 0.08,
            color: "#ffffff",
            fontWeight: 900,
            animation: "zoomIn",
          }),
          shape({
            shape: "rect",
            fill: "#ffffff",
            x: 0.15,
            y: 0.5,
            width: 0.7,
            height: 0.12,
            borderRadius: 0.06,
            animation: "slideUp",
            animationDelay: 0.3,
          }),
          text({
            text: brand.website,
            y: 0.525,
            fontSize: 0.055,
            color: palette.secondary,
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.5,
          }),
          text({
            text: `Or call ${brand.phone}`,
            y: 0.8,
            fontSize: 0.038,
            color: "#ffffff",
            opacity: 0.9,
            fontWeight: 600,
            animation: "fadeIn",
            animationDelay: 0.7,
          }),
        ],
      }),
    ],
  },
];

/* ──────────────────────────────────────────────────────────────────────────
 *  VIRAL TEMPLATES — TikTok / Reels native, optimized for shares & saves
 * ────────────────────────────────────────────────────────────────────────── */

const VIRAL_TEMPLATES: AdTemplate[] = [
  {
    id: "tpl-viral-pov",
    name: "POV — Pattern Interrupt (Viral)",
    goal: "before-after",
    description:
      "Native POV opener that mimics organic Reels. Captions burned in for muted scrolling. Designed to maximize 3-second view rate.",
    recommendedAspect: "9:16",
    preview: {
      background: grad("#0a0a0a", "#1f2937"),
      headline: "POV:",
      sub: "you finally cleared the garage",
      accent: "#FBBF24",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "POV Hook",
        duration: 1.6,
        background: grad("#0a0a0a", "#1f2937", 180),
        transitionIn: "none",
        layers: [
          shape({
            shape: "rect",
            fill: "#FBBF24",
            x: 0.05,
            y: 0.08,
            width: 0.18,
            height: 0.06,
            borderRadius: 0.02,
          }),
          text({
            text: "POV",
            x: 0.05,
            y: 0.094,
            width: 0.18,
            height: 0.05,
            fontSize: 0.04,
            color: "#0a0a0a",
            fontWeight: 900,
            letterSpacing: 0.04,
          }),
          text({
            text: "you finally booked\nthe garage cleanout.",
            y: 0.38,
            fontSize: 0.075,
            color: "#ffffff",
            fontWeight: 900,
            lineHeight: 1.1,
            animation: "slideUp",
            animationDelay: 0.1,
            animationDuration: 0.4,
          }),
          text({
            text: "(3 years overdue)",
            y: 0.68,
            fontSize: 0.045,
            color: "#FBBF24",
            fontWeight: 700,
            italic: true,
            animation: "fadeIn",
            animationDelay: 0.6,
          }),
        ],
      }),
      scene({
        name: "Before tease",
        duration: 1.4,
        background: brand.beforeImage
          ? { kind: "image", src: brand.beforeImage, fit: "cover", overlay: "rgba(0,0,0,0.45)" }
          : grad("#7f1d1d", "#1f2937", 180),
        transitionIn: "slideLeft",
        transitionInDuration: 0.2,
        layers: [
          text({
            text: "Today.",
            y: 0.78,
            fontSize: 0.07,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
          }),
        ],
      }),
      scene({
        name: "After payoff",
        duration: 1.8,
        background: brand.afterImage
          ? { kind: "image", src: brand.afterImage, fit: "cover" }
          : grad("#16a34a", "#052e16", 180),
        transitionIn: "slideLeft",
        transitionInDuration: 0.15,
        layers: [
          text({
            text: "Under an hour later.",
            y: 0.78,
            fontSize: 0.065,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "slideUp",
          }),
        ],
      }),
      scene({
        name: "Receipt",
        duration: 1.6,
        background: grad("#0a0a0a", "#1f2937", 200),
        transitionIn: "zoom",
        layers: [
          text({
            text: "Booked online · Same-day",
            y: 0.3,
            fontSize: 0.05,
            color: "#94a3b8",
            fontWeight: 600,
            animation: "fadeIn",
          }),
          text({
            text: brand.offer,
            y: 0.42,
            fontSize: 0.07,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.2,
          }),
          shape({
            shape: "rect",
            fill: "#FBBF24",
            x: 0.15,
            y: 0.6,
            width: 0.7,
            height: 0.1,
            borderRadius: 0.05,
            animation: "zoomIn",
            animationDelay: 0.5,
          }),
          text({
            text: brand.website,
            y: 0.62,
            fontSize: 0.05,
            color: "#0a0a0a",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.7,
          }),
        ],
      }),
    ],
  },
  {
    id: "tpl-viral-tell-me",
    name: 'Tell Me You... (Viral)',
    goal: "social-proof",
    description:
      'The "tell me you... without telling me" pattern — high save rate and very share-friendly. Adapted for the Tampa hoarder-garage archetype.',
    recommendedAspect: "9:16",
    preview: {
      background: grad("#facc15", "#dc2626"),
      headline: "Tell me you...",
      sub: "have a Tampa hoarder garage",
      accent: "#0a0a0a",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Hook",
        duration: 2.2,
        background: grad("#0a0a0a", "#1f2937", 180),
        transitionIn: "none",
        layers: [
          text({
            text: "Tell me you have a Tampa hoarder garage",
            y: 0.28,
            fontSize: 0.06,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
            animationDuration: 0.4,
          }),
          text({
            text: "without telling me you have a Tampa hoarder garage.",
            y: 0.5,
            fontSize: 0.045,
            color: "#FBBF24",
            fontWeight: 700,
            italic: true,
            animation: "fadeIn",
            animationDelay: 0.4,
          }),
          text({
            text: "I'll start.",
            y: 0.78,
            fontSize: 0.05,
            color: "#ffffff",
            fontWeight: 800,
            animation: "fadeIn",
            animationDelay: 0.9,
          }),
        ],
      }),
      scene({
        name: "Checklist",
        duration: 3.0,
        background: grad("#1e293b", "#0a0a0a", 180),
        transitionIn: "slideUp",
        layers: [
          text({
            text: "✓ A broken treadmill nobody touches",
            y: 0.2,
            x: 0.08,
            width: 0.84,
            height: 0.08,
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            animation: "slideLeft",
            animationDelay: 0.1,
          }),
          text({
            text: "✓ Patio set from two hurricanes ago",
            y: 0.32,
            x: 0.08,
            width: 0.84,
            height: 0.08,
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            animation: "slideLeft",
            animationDelay: 0.35,
          }),
          text({
            text: "✓ Hot tub that hasn't worked since 2022",
            y: 0.44,
            x: 0.08,
            width: 0.84,
            height: 0.08,
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            animation: "slideLeft",
            animationDelay: 0.6,
          }),
          text({
            text: "✓ Mystery boxes labeled \"misc\"",
            y: 0.56,
            x: 0.08,
            width: 0.84,
            height: 0.08,
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            animation: "slideLeft",
            animationDelay: 0.85,
          }),
          text({
            text: "✓ Pool floats from when the kids were 9",
            y: 0.68,
            x: 0.08,
            width: 0.84,
            height: 0.08,
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 700,
            align: "left",
            animation: "slideLeft",
            animationDelay: 1.1,
          }),
          text({
            text: "We haul it all. Same day.",
            y: 0.84,
            fontSize: 0.05,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 1.5,
          }),
        ],
      }),
      scene({
        name: "CTA",
        duration: 2.0,
        background: grad("#FBBF24", "#dc2626", 150),
        transitionIn: "zoom",
        layers: [
          text({
            text: brand.cta,
            y: 0.3,
            fontSize: 0.08,
            color: "#0a0a0a",
            fontWeight: 900,
            animation: "slideUp",
          }),
          shape({
            shape: "rect",
            fill: "#0a0a0a",
            x: 0.15,
            y: 0.52,
            width: 0.7,
            height: 0.12,
            borderRadius: 0.06,
            animation: "zoomIn",
            animationDelay: 0.4,
          }),
          text({
            text: brand.website,
            y: 0.545,
            fontSize: 0.055,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.6,
          }),
          text({
            text: brand.phone,
            y: 0.78,
            fontSize: 0.045,
            color: "#0a0a0a",
            fontWeight: 800,
            animation: "fadeIn",
            animationDelay: 0.8,
          }),
        ],
      }),
    ],
  },
  {
    id: "tpl-viral-rate-this",
    name: "Rate This Cleanout (Viral)",
    goal: "before-after",
    description:
      'The "rate this out of 10" pattern: invites comments + drives saves. Perfect for showcasing a real before/after with engagement bait that doesn\'t trip Meta.',
    recommendedAspect: "9:16",
    preview: {
      background: grad("#0369a1", "#0a0a0a"),
      headline: "Rate this Tampa garage",
      sub: "cleanout / 10",
      accent: "#FBBF24",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Hook",
        duration: 1.8,
        background: grad("#0a0a0a", "#0369a1", 180),
        transitionIn: "none",
        layers: [
          text({
            text: "Rate this Tampa garage cleanout",
            y: 0.36,
            fontSize: 0.062,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
            animationDuration: 0.4,
          }),
          text({
            text: "/ 10",
            y: 0.56,
            fontSize: 0.12,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "zoomIn",
            animationDelay: 0.4,
          }),
        ],
      }),
      scene({
        name: "Before",
        duration: 1.6,
        background: brand.beforeImage
          ? { kind: "image", src: brand.beforeImage, fit: "cover", overlay: "rgba(0,0,0,0.35)" }
          : grad("#7f1d1d", "#1f2937", 180),
        transitionIn: "slideLeft",
        transitionInDuration: 0.2,
        layers: [
          shape({
            shape: "rect",
            fill: "#dc2626",
            x: 0.08,
            y: 0.08,
            width: 0.3,
            height: 0.07,
            borderRadius: 0.03,
          }),
          text({
            text: "BEFORE",
            x: 0.08,
            y: 0.094,
            width: 0.3,
            height: 0.05,
            fontSize: 0.04,
            color: "#ffffff",
            fontWeight: 900,
            letterSpacing: 0.05,
          }),
        ],
      }),
      scene({
        name: "After",
        duration: 1.8,
        background: brand.afterImage
          ? { kind: "image", src: brand.afterImage, fit: "cover" }
          : grad("#16a34a", "#052e16", 180),
        transitionIn: "slideLeft",
        transitionInDuration: 0.15,
        layers: [
          shape({
            shape: "rect",
            fill: "#16a34a",
            x: 0.62,
            y: 0.08,
            width: 0.3,
            height: 0.07,
            borderRadius: 0.03,
          }),
          text({
            text: "AFTER",
            x: 0.62,
            y: 0.094,
            width: 0.3,
            height: 0.05,
            fontSize: 0.04,
            color: "#ffffff",
            fontWeight: 900,
            letterSpacing: 0.05,
          }),
          text({
            text: "Drop your score 👇",
            y: 0.82,
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 800,
            animation: "pulse",
            animationDelay: 0.4,
          }),
        ],
      }),
      scene({
        name: "Score & CTA",
        duration: 2.2,
        background: grad("#0a0a0a", "#0369a1", 180),
        transitionIn: "zoom",
        layers: [
          text({
            text: "We give it a",
            y: 0.18,
            fontSize: 0.048,
            color: "#94a3b8",
            fontWeight: 600,
            animation: "fadeIn",
          }),
          text({
            text: "10/10",
            y: 0.3,
            fontSize: 0.15,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "zoomIn",
            animationDelay: 0.2,
          }),
          text({
            text: "Want yours next?",
            y: 0.58,
            fontSize: 0.05,
            color: "#ffffff",
            fontWeight: 800,
            animation: "fadeIn",
            animationDelay: 0.6,
          }),
          shape({
            shape: "rect",
            fill: "#FBBF24",
            x: 0.15,
            y: 0.74,
            width: 0.7,
            height: 0.1,
            borderRadius: 0.05,
            animation: "slideUp",
            animationDelay: 0.8,
          }),
          text({
            text: brand.website,
            y: 0.76,
            fontSize: 0.05,
            color: "#0a0a0a",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 1.0,
          }),
        ],
      }),
    ],
  },
];

/* ──────────────────────────────────────────────────────────────────────────
 *  FUNNY TEMPLATES — humor-first formats. Comedy = shares = reach.
 * ────────────────────────────────────────────────────────────────────────── */

const FUNNY_TEMPLATES: AdTemplate[] = [
  /* ─── 1. "Things we pulled out of one Tampa garage" — reveal list ─── */
  {
    id: "tpl-funny-garage-finds",
    name: "Things We Pulled Out (Funny)",
    goal: "before-after",
    description:
      "Confessional reveal list of absurd things found in a real Tampa garage. Big watch-through and high share rate.",
    recommendedAspect: "9:16",
    preview: {
      background: grad("#0a0a0a", "#1f2937"),
      headline: "Things we pulled out…",
      sub: "of ONE Tampa garage",
      accent: "#FBBF24",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Hook",
        duration: 1.8,
        background: grad("#0a0a0a", "#1f2937", 180),
        transitionIn: "none",
        layers: [
          text({
            text: "Things we pulled out",
            y: 0.32,
            fontSize: 0.07,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
            animationDuration: 0.4,
          }),
          text({
            text: "of ONE Tampa garage yesterday:",
            y: 0.5,
            fontSize: 0.052,
            color: "#FBBF24",
            fontWeight: 700,
            italic: true,
            animation: "fadeIn",
            animationDelay: 0.4,
          }),
        ],
      }),
      scene({
        name: "List",
        duration: 4.0,
        background: grad("#1e293b", "#0a0a0a", 200),
        transitionIn: "slideUp",
        layers: [
          text({
            text: "• A treadmill from 1987",
            y: 0.1,
            x: 0.08,
            width: 0.84,
            height: 0.08,
            align: "left",
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 0.1,
          }),
          text({
            text: "• 47 paint cans",
            y: 0.22,
            x: 0.08,
            width: 0.84,
            height: 0.08,
            align: "left",
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 0.45,
          }),
          text({
            text: "• 3 broken patio sets",
            y: 0.34,
            x: 0.08,
            width: 0.84,
            height: 0.08,
            align: "left",
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 0.8,
          }),
          text({
            text: "• A hot tub from 2009",
            y: 0.46,
            x: 0.08,
            width: 0.84,
            height: 0.08,
            align: "left",
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 1.15,
          }),
          text({
            text: "• Boxes labeled \"mystery\"",
            y: 0.58,
            x: 0.08,
            width: 0.84,
            height: 0.08,
            align: "left",
            fontSize: 0.045,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 1.5,
          }),
          text({
            text: "• Her ex-husband's tools",
            y: 0.7,
            x: 0.08,
            width: 0.84,
            height: 0.08,
            align: "left",
            fontSize: 0.045,
            color: "#FBBF24",
            fontWeight: 800,
            animation: "slideLeft",
            animationDelay: 1.85,
          }),
          text({
            text: "& one VERY relieved homeowner.",
            y: 0.86,
            fontSize: 0.04,
            color: "#86efac",
            fontWeight: 700,
            italic: true,
            animation: "fadeIn",
            animationDelay: 2.4,
          }),
        ],
      }),
      scene({
        name: "CTA",
        duration: 2.0,
        background: grad(palette.primary, "#7c5a00", 150),
        transitionIn: "zoom",
        layers: [
          text({
            text: "Your turn.",
            y: 0.28,
            fontSize: 0.1,
            color: "#0a0a0a",
            fontWeight: 900,
            animation: "zoomIn",
          }),
          shape({
            shape: "rect",
            fill: "#0a0a0a",
            x: 0.15,
            y: 0.5,
            width: 0.7,
            height: 0.12,
            borderRadius: 0.06,
            animation: "slideUp",
            animationDelay: 0.3,
          }),
          text({
            text: brand.website,
            y: 0.525,
            fontSize: 0.055,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.5,
          }),
          text({
            text: `or ${brand.phone}`,
            y: 0.78,
            fontSize: 0.04,
            color: "#0a0a0a",
            fontWeight: 700,
            animation: "fadeIn",
            animationDelay: 0.7,
          }),
        ],
      }),
    ],
  },

  /* ─── 2. "Tier list of stuff in your garage" — meme format ──────────── */
  {
    id: "tpl-funny-tier-list",
    name: "Garage Tier List (Funny)",
    goal: "before-after",
    description:
      "Meme-format tier list ranking the junk in your garage. Highly shareable on Reels because viewers tag friends who own the same stuff.",
    recommendedAspect: "9:16",
    preview: {
      background: grad("#facc15", "#0a0a0a"),
      headline: "Tampa garage tier list",
      sub: "We haul ALL tiers.",
      accent: "#dc2626",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Hook",
        duration: 1.5,
        background: grad("#0a0a0a", "#1f2937", 180),
        transitionIn: "none",
        layers: [
          text({
            text: "Tampa garage tier list",
            y: 0.42,
            fontSize: 0.072,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
          }),
          text({
            text: "(brutally honest)",
            y: 0.58,
            fontSize: 0.04,
            color: "#FBBF24",
            italic: true,
            fontWeight: 600,
            animation: "fadeIn",
            animationDelay: 0.3,
          }),
        ],
      }),
      scene({
        name: "Tiers",
        duration: 4.0,
        background: grad("#0a0a0a", "#1e293b", 180),
        transitionIn: "slideUp",
        layers: [
          // S tier (green)
          shape({ shape: "rect", fill: "#16a34a", x: 0.05, y: 0.1, width: 0.12, height: 0.1, borderRadius: 0.02 }),
          text({ text: "S", x: 0.05, y: 0.115, width: 0.12, height: 0.08, fontSize: 0.05, color: "#fff", fontWeight: 900 }),
          text({
            text: "Useful stuff your wife keeps anyway",
            y: 0.115,
            x: 0.2,
            width: 0.75,
            height: 0.08,
            align: "left",
            fontSize: 0.035,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 0.1,
          }),
          // A tier (yellow)
          shape({ shape: "rect", fill: "#FBBF24", x: 0.05, y: 0.24, width: 0.12, height: 0.1, borderRadius: 0.02 }),
          text({ text: "A", x: 0.05, y: 0.255, width: 0.12, height: 0.08, fontSize: 0.05, color: "#0a0a0a", fontWeight: 900 }),
          text({
            text: "The treadmill (3 uses, $400)",
            y: 0.255,
            x: 0.2,
            width: 0.75,
            height: 0.08,
            align: "left",
            fontSize: 0.035,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 0.35,
          }),
          // B tier (orange)
          shape({ shape: "rect", fill: "#f97316", x: 0.05, y: 0.38, width: 0.12, height: 0.1, borderRadius: 0.02 }),
          text({ text: "B", x: 0.05, y: 0.395, width: 0.12, height: 0.08, fontSize: 0.05, color: "#0a0a0a", fontWeight: 900 }),
          text({
            text: "Patio set from two hurricanes ago",
            y: 0.395,
            x: 0.2,
            width: 0.75,
            height: 0.08,
            align: "left",
            fontSize: 0.035,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 0.6,
          }),
          // C tier (red)
          shape({ shape: "rect", fill: "#dc2626", x: 0.05, y: 0.52, width: 0.12, height: 0.1, borderRadius: 0.02 }),
          text({ text: "C", x: 0.05, y: 0.535, width: 0.12, height: 0.08, fontSize: 0.05, color: "#fff", fontWeight: 900 }),
          text({
            text: "Boxes labeled \"misc\"",
            y: 0.535,
            x: 0.2,
            width: 0.75,
            height: 0.08,
            align: "left",
            fontSize: 0.035,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 0.85,
          }),
          // F tier (dark)
          shape({ shape: "rect", fill: "#0a0a0a", stroke: "#dc2626", strokeWidth: 0.006, x: 0.05, y: 0.66, width: 0.12, height: 0.1, borderRadius: 0.02 }),
          text({ text: "F", x: 0.05, y: 0.675, width: 0.12, height: 0.08, fontSize: 0.05, color: "#dc2626", fontWeight: 900 }),
          text({
            text: "Your ex's stuff (still there)",
            y: 0.675,
            x: 0.2,
            width: 0.75,
            height: 0.08,
            align: "left",
            fontSize: 0.035,
            color: "#fda4af",
            fontWeight: 700,
            italic: true,
            animation: "slideLeft",
            animationDelay: 1.1,
          }),
          text({
            text: "We haul ALL tiers. Same day.",
            y: 0.86,
            fontSize: 0.045,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 1.5,
          }),
        ],
      }),
      scene({
        name: "CTA",
        duration: 1.8,
        background: grad(palette.primary, "#7c5a00", 150),
        transitionIn: "zoom",
        layers: [
          text({
            text: brand.cta,
            y: 0.32,
            fontSize: 0.075,
            color: "#0a0a0a",
            fontWeight: 900,
            animation: "slideUp",
          }),
          shape({
            shape: "rect",
            fill: "#0a0a0a",
            x: 0.15,
            y: 0.52,
            width: 0.7,
            height: 0.12,
            borderRadius: 0.06,
            animation: "zoomIn",
            animationDelay: 0.3,
          }),
          text({
            text: brand.website,
            y: 0.545,
            fontSize: 0.055,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.5,
          }),
        ],
      }),
    ],
  },

  /* ─── 3. "Things our crew has heard" — dialog ──────────────────────── */
  {
    id: "tpl-funny-overheard",
    name: "Things Our Crew Heard (Funny)",
    goal: "trust-builder",
    description:
      "Real things Tampa customers say when the crew arrives. Funny + relatable + 'we don't judge' = trust + shareability.",
    recommendedAspect: "9:16",
    preview: {
      background: grad("#0a0a0a", "#0369a1"),
      headline: "Things our Tampa crew",
      sub: "actually heard last week",
      accent: "#FBBF24",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Hook",
        duration: 1.8,
        background: grad("#0a0a0a", "#0369a1", 180),
        transitionIn: "none",
        layers: [
          text({
            text: "Things our Tampa crew",
            y: 0.36,
            fontSize: 0.062,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
          }),
          text({
            text: "actually heard last week:",
            y: 0.5,
            fontSize: 0.054,
            color: "#FBBF24",
            fontWeight: 700,
            italic: true,
            animation: "fadeIn",
            animationDelay: 0.3,
          }),
        ],
      }),
      scene({
        name: "Quotes",
        duration: 4.2,
        background: grad("#0f172a", "#0a0a0a", 180),
        transitionIn: "slideUp",
        layers: [
          text({
            text: "\"Just take it all.\"",
            y: 0.1,
            x: 0.06,
            width: 0.88,
            height: 0.1,
            fontSize: 0.052,
            color: "#ffffff",
            fontWeight: 800,
            animation: "slideLeft",
            animationDelay: 0.1,
          }),
          text({
            text: "\"I don't even know what's in there.\"",
            y: 0.24,
            x: 0.06,
            width: 0.88,
            height: 0.1,
            fontSize: 0.046,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 0.5,
          }),
          text({
            text: "\"My wife doesn't know I'm calling.\"",
            y: 0.38,
            x: 0.06,
            width: 0.88,
            height: 0.1,
            fontSize: 0.046,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 0.9,
          }),
          text({
            text: "\"Please hurry before he gets home.\"",
            y: 0.52,
            x: 0.06,
            width: 0.88,
            height: 0.1,
            fontSize: 0.046,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideLeft",
            animationDelay: 1.3,
          }),
          text({
            text: "\"Some of this is technically my ex's.\"",
            y: 0.66,
            x: 0.06,
            width: 0.88,
            height: 0.1,
            fontSize: 0.046,
            color: "#fda4af",
            fontWeight: 700,
            italic: true,
            animation: "slideLeft",
            animationDelay: 1.7,
          }),
          text({
            text: "We don't judge. We haul.",
            y: 0.86,
            fontSize: 0.052,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 2.3,
          }),
        ],
      }),
      scene({
        name: "CTA",
        duration: 1.8,
        background: grad(palette.primary, "#7c5a00", 150),
        transitionIn: "zoom",
        layers: [
          text({
            text: "Your secret's safe.",
            y: 0.28,
            fontSize: 0.062,
            color: "#0a0a0a",
            fontWeight: 900,
            animation: "slideUp",
          }),
          shape({
            shape: "rect",
            fill: "#0a0a0a",
            x: 0.15,
            y: 0.5,
            width: 0.7,
            height: 0.12,
            borderRadius: 0.06,
            animation: "zoomIn",
            animationDelay: 0.3,
          }),
          text({
            text: brand.website,
            y: 0.525,
            fontSize: 0.055,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.5,
          }),
        ],
      }),
    ],
  },

  /* ─── 4. "It's NOT junk" — comedy contrast ──────────────────────────── */
  {
    id: "tpl-funny-not-junk",
    name: "It's NOT Junk (Funny)",
    goal: "before-after",
    description:
      "Comedy escalation — every absurd thing he insists isn't junk. Visual-text contrast pattern that drives massive shares in family/couple-targeted audiences.",
    recommendedAspect: "9:16",
    preview: {
      background: grad("#dc2626", "#0a0a0a"),
      headline: '"It\'s not junk."',
      sub: "We respectfully disagree.",
      accent: "#FBBF24",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Setup",
        duration: 1.6,
        background: grad("#0a0a0a", "#1f2937", 180),
        transitionIn: "none",
        layers: [
          text({
            text: "When he says…",
            y: 0.42,
            fontSize: 0.06,
            color: "#94a3b8",
            fontWeight: 700,
            italic: true,
            animation: "fadeIn",
          }),
          text({
            text: "\"It's not junk.\"",
            y: 0.56,
            fontSize: 0.085,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.3,
          }),
        ],
      }),
      scene({
        name: "Beat 1",
        duration: 1.2,
        background: grad("#7f1d1d", "#0a0a0a", 180),
        transitionIn: "slideLeft",
        transitionInDuration: 0.2,
        layers: [
          text({
            text: "The broken treadmill:",
            y: 0.35,
            fontSize: 0.055,
            color: "#fda4af",
            fontWeight: 700,
            italic: true,
            animation: "fadeIn",
          }),
          text({
            text: "\"Not junk.\"",
            y: 0.55,
            fontSize: 0.08,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.2,
          }),
        ],
      }),
      scene({
        name: "Beat 2",
        duration: 1.2,
        background: grad("#7f1d1d", "#0a0a0a", 180),
        transitionIn: "slideLeft",
        transitionInDuration: 0.2,
        layers: [
          text({
            text: "The 8 broken patio chairs:",
            y: 0.35,
            fontSize: 0.052,
            color: "#fda4af",
            fontWeight: 700,
            italic: true,
            animation: "fadeIn",
          }),
          text({
            text: "\"Not junk.\"",
            y: 0.55,
            fontSize: 0.08,
            color: "#ffffff",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.2,
          }),
        ],
      }),
      scene({
        name: "Beat 3",
        duration: 1.4,
        background: grad("#7f1d1d", "#0a0a0a", 180),
        transitionIn: "slideLeft",
        transitionInDuration: 0.2,
        layers: [
          text({
            text: "The 2009 hot tub:",
            y: 0.35,
            fontSize: 0.055,
            color: "#fda4af",
            fontWeight: 700,
            italic: true,
            animation: "fadeIn",
          }),
          text({
            text: "\"DEFINITELY not junk.\"",
            y: 0.55,
            fontSize: 0.065,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.2,
          }),
        ],
      }),
      scene({
        name: "Punchline",
        duration: 2.0,
        background: grad(palette.primary, "#7c5a00", 150),
        transitionIn: "zoom",
        layers: [
          text({
            text: "We respectfully",
            y: 0.32,
            fontSize: 0.062,
            color: "#0a0a0a",
            fontWeight: 800,
            italic: true,
            animation: "slideUp",
          }),
          text({
            text: "disagree.",
            y: 0.46,
            fontSize: 0.1,
            color: "#0a0a0a",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.3,
          }),
          shape({
            shape: "rect",
            fill: "#0a0a0a",
            x: 0.15,
            y: 0.66,
            width: 0.7,
            height: 0.11,
            borderRadius: 0.06,
            animation: "zoomIn",
            animationDelay: 0.6,
          }),
          text({
            text: brand.website,
            y: 0.68,
            fontSize: 0.055,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.8,
          }),
        ],
      }),
    ],
  },

  /* ─── 5. "POV: your Sunday morning garage" — relatable ─────────────── */
  {
    id: "tpl-funny-sunday-garage",
    name: "Sunday Morning Garage (Funny)",
    goal: "before-after",
    description:
      "Relatable comedy — the universal Tampa-homeowner experience of trying to walk through their own garage. Closes with the BJA punchline.",
    recommendedAspect: "9:16",
    preview: {
      background: grad("#FBBF24", "#7c5a00"),
      headline: "POV: Sunday morning",
      sub: "in your Tampa garage",
      accent: "#0a0a0a",
    },
    build: ({ brand, palette }) => [
      scene({
        name: "Setup",
        duration: 1.6,
        background: grad("#1f2937", "#0a0a0a", 180),
        transitionIn: "none",
        layers: [
          text({
            text: "POV:",
            y: 0.3,
            fontSize: 0.11,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "zoomIn",
            animationDuration: 0.3,
          }),
          text({
            text: "Sunday morning in your",
            y: 0.52,
            fontSize: 0.05,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideUp",
            animationDelay: 0.2,
          }),
          text({
            text: "Tampa garage.",
            y: 0.6,
            fontSize: 0.05,
            color: "#ffffff",
            fontWeight: 700,
            animation: "slideUp",
            animationDelay: 0.35,
          }),
        ],
      }),
      scene({
        name: "Beat 1",
        duration: 1.4,
        background: grad("#7f1d1d", "#0a0a0a", 180),
        transitionIn: "slideUp",
        transitionInDuration: 0.2,
        layers: [
          text({
            text: "You go in for ONE thing.",
            y: 0.42,
            fontSize: 0.056,
            color: "#ffffff",
            fontWeight: 800,
            animation: "slideUp",
          }),
        ],
      }),
      scene({
        name: "Beat 2",
        duration: 1.4,
        background: grad("#7f1d1d", "#0a0a0a", 180),
        transitionIn: "slideUp",
        transitionInDuration: 0.2,
        layers: [
          text({
            text: "You knock over four.",
            y: 0.42,
            fontSize: 0.056,
            color: "#fda4af",
            fontWeight: 800,
            animation: "slideUp",
          }),
        ],
      }),
      scene({
        name: "Beat 3",
        duration: 1.6,
        background: grad("#7f1d1d", "#0a0a0a", 180),
        transitionIn: "slideUp",
        transitionInDuration: 0.2,
        layers: [
          text({
            text: "Now an avalanche of",
            y: 0.36,
            fontSize: 0.05,
            color: "#ffffff",
            fontWeight: 800,
            animation: "slideUp",
          }),
          text({
            text: "Christmas decorations",
            y: 0.5,
            fontSize: 0.05,
            color: "#ffffff",
            fontWeight: 800,
            animation: "slideUp",
            animationDelay: 0.2,
          }),
          text({
            text: "(from 2017).",
            y: 0.64,
            fontSize: 0.05,
            color: "#FBBF24",
            italic: true,
            fontWeight: 800,
            animation: "slideUp",
            animationDelay: 0.4,
          }),
        ],
      }),
      scene({
        name: "Solution",
        duration: 1.8,
        background: grad(palette.primary, "#7c5a00", 150),
        transitionIn: "zoom",
        layers: [
          text({
            text: "Or…",
            y: 0.2,
            fontSize: 0.07,
            color: "#0a0a0a",
            italic: true,
            fontWeight: 700,
            animation: "fadeIn",
          }),
          text({
            text: "you call us.",
            y: 0.32,
            fontSize: 0.1,
            color: "#0a0a0a",
            fontWeight: 900,
            animation: "slideUp",
            animationDelay: 0.2,
          }),
          shape({
            shape: "rect",
            fill: "#0a0a0a",
            x: 0.15,
            y: 0.56,
            width: 0.7,
            height: 0.12,
            borderRadius: 0.06,
            animation: "zoomIn",
            animationDelay: 0.5,
          }),
          text({
            text: brand.website,
            y: 0.585,
            fontSize: 0.055,
            color: "#FBBF24",
            fontWeight: 900,
            animation: "fadeIn",
            animationDelay: 0.7,
          }),
          text({
            text: `or ${brand.phone}`,
            y: 0.78,
            fontSize: 0.038,
            color: "#0a0a0a",
            fontWeight: 700,
            animation: "fadeIn",
            animationDelay: 0.9,
          }),
        ],
      }),
    ],
  },
];

const ALL_TEMPLATES = [...TEMPLATES, ...VIRAL_TEMPLATES, ...FUNNY_TEMPLATES];

export function listTemplates(): AdTemplate[] {
  return ALL_TEMPLATES;
}

export function listViralTemplates(): AdTemplate[] {
  return VIRAL_TEMPLATES;
}

export function getTemplate(id: string): AdTemplate | undefined {
  return TEMPLATES.find((t) => t.id === id);
}
